### PR TITLE
Regions and parameters for G327 B6 and G338 B3

### PR DESCRIPTION
**Pull request by folguinch**
Hi Adam, here are the regions and input parameters for these sources. There are also some changes to make the beginning of `continuum_imaging_selfcal.py` the same as `continuum_imaging.py`, but I saw you made some changes to the latter so the former may need the same fix. There are also some changes in `split_windows.py` for command line usage. I added a save model and residual in the `continuum_imaging.py` script but forgot to take it out before this pull request, if you want I could create a new request without those lines. The `crtf` masks were removed because they are not used in the final imaging.

### CODE REVIEW

**Comment by keflavich** [comment]
Looks good, thanks.  I'll work on merging this.  Yes, as you said, I made some changes that were necessary to avoid the scripts breaking under other circumstances.

**Comment by keflavich** [comment]
@folguinch why do your filenames lack the `uid` name?  They should look like, e.g.:
`G338.93_B6_uid___A001_X1296_X14f_continuum_merged_12M_robust0.image.tt0.fits`
but instead they appear as, e.g.:
`G338.93_B3__continuum_merged_12M_robust0_selfcal2_finaliter.image.tt0.fits`

The missing uid information is a problem we need to resolve.

**Comment by folguinch** [comment]
@keflavich This is in 7m `calibrated` directory:
```bash
-rw-r--r--  1 fernndoi adcusers   80 Oct  4 16:27 G338.93_B3
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:36 G338.93_B3__continuum_merged.cal.ms
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  8 15:46 G338.93_B3__continuum_merged_12M.cal.ms
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:39 G338.93_B3__continuum_merged_bsens.cal.ms
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:34 continuum_uid___A002_Xc7e4e4_X3096.ms.split.cal.cont
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:34 continuum_uid___A002_Xc7e4e4_X3096.ms.split.cal_bsens.cont
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:34 continuum_uid___A002_Xc7e4e4_X352d.ms.split.cal.cont
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:34 continuum_uid___A002_Xc7e4e4_X352d.ms.split.cal_bsens.cont
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:34 continuum_uid___A002_Xc82bb8_X2b1d.ms.split.cal.cont
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 16:35 continuum_uid___A002_Xc82bb8_X2b1d.ms.split.cal_bsens.cont
drwxr-xr-x 27 fernndoi adcusers 4.0K Sep 21  2018 uid___A002_Xc7e4e4_X3096.ms.split.cal
drwxr-xr-x  6 fernndoi adcusers  211 Oct  4 16:34 uid___A002_Xc7e4e4_X3096.ms.split.cal.flagversions
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:38 uid___A002_Xc7e4e4_X3096_G338.93_B3_spw0.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:38 uid___A002_Xc7e4e4_X3096_G338.93_B3_spw1.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:39 uid___A002_Xc7e4e4_X3096_G338.93_B3_spw2.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:40 uid___A002_Xc7e4e4_X3096_G338.93_B3_spw3.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Sep 21  2018 uid___A002_Xc7e4e4_X352d.ms.split.cal
drwxr-xr-x  6 fernndoi adcusers  211 Oct  4 16:34 uid___A002_Xc7e4e4_X352d.ms.split.cal.flagversions
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:38 uid___A002_Xc7e4e4_X352d_G338.93_B3_spw0.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:38 uid___A002_Xc7e4e4_X352d_G338.93_B3_spw1.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:39 uid___A002_Xc7e4e4_X352d_G338.93_B3_spw2.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:40 uid___A002_Xc7e4e4_X352d_G338.93_B3_spw3.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Sep 21  2018 uid___A002_Xc82bb8_X2b1d.ms.split.cal
drwxr-xr-x  6 fernndoi adcusers  211 Oct  4 16:34 uid___A002_Xc82bb8_X2b1d.ms.split.cal.flagversions
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:38 uid___A002_Xc82bb8_X2b1d_G338.93_B3_spw0.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:39 uid___A002_Xc82bb8_X2b1d_G338.93_B3_spw1.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:39 uid___A002_Xc82bb8_X2b1d_G338.93_B3_spw2.split
drwxr-xr-x 27 fernndoi adcusers 4.0K Oct  4 14:40 uid___A002_Xc82bb8_X2b1d_G338.93_B3_spw3.split
```
It seems that the `uid` name was lost when it split the ms for the source. I guess this is in the `split_windows.py` script?

**Comment by keflavich** [comment]
Interesting.... that doesn't seem to have affected anyone else.  Let's try to figure out what caused it; I'm concerned now.

**Comment by folguinch** [comment]
What happens when there is more than 1 EB? which `uid` name should adopt?

**Comment by keflavich** [comment]
It will be the member ous id of the last EB encountered.  So it should be the MOUS of one of the two 12m configurations, I believe, but it's possible that it would end up as the MOUS ID of the 7m configuration even if you exclude the 7m data.... I'm not sure of that at a glance.

**Pull request merged**
