### PR TITLE
Update imaging_parameters.py

### PR DESCRIPTION
**Pull request by manferna**
changed/added some autoMT parameters to W51E constsub

### CODE REVIEW

**Comment by keflavich** [comment]
Manuel, can you discuss why these specific changes?  Have you done comparison work?

**Comment by manferna** [comment]
I added some comments. For now, based on my trials, I think these parameters may work better than the current ones, at least for W51E.

**Comment by keflavich** [comment]
I'm keeping this unmerged now because I'm also testing a different set of parameters for W51-E; we'll merge these if you decide they're best.

**Comment by manferna** [comment]
It's ok, Adam.
I think it is a very good idea producing a round of raw pb-masked cubes.
That way, we will have first simple-cleaning maps to compare with and will
be able to identify problematic or harder cubes.
Cheers!

*******************************************************
Manuel Fernández López

Instituto Argentino de Radioastronomía
manferna@iar.unlp.edu.ar
manferna@gmail.com

fringe http://fringe.iar.unlp.edu.ar

**Comment by keflavich** [comment]
We've changed these parameters in other threads now, so I'm closing this.

**Pull request closed without merging**
