### PR TITLE
continuum_imaging_both.py

### PR DESCRIPTION
**Pull request by rgalvanmadrid**
Turns out the crashes I had were not because of the presence of a PM antenna in one EB, but because of the format of the antenna lists for the "best sensitivity" imaging. There, several ms's are used, so one antenna list with several sublists is needed. The previous code concatenated all ms antenna lists to crate a single one, which then was passed to each of the ms's to image. So when, say, antenna "DA41" was not in one of the ms's then the imaging crashed.

### CODE REVIEW

**Comment by rgalvanmadrid** [comment]
Looking at the comparison, I think that there are a few lines that you added after I forked the repository into my computer ...

**Comment by keflavich** [comment]
Indeed, I think I've fixed the issues you noticed.  I should have reported that.

Regarding setting variables locally, if you want to run these scripts in a CASA session, you can just do:

```
CASA <1>: exclude_7m = True

CASA <2>: %run -i continuum_imaging.py
```
and it will work as if you'd specified `EXCLUDE_7M=True` on the shell command line.  

Note that you should _not_ add `sys.path.append('.')` when running these files.  They are not meant to be executed from the code directory.  The structure should be something like this:

code lives in `..../almaimf/reduction/`
files live in `/somewhere/else/almaimf/`
and you run the code in `/somewhere/else/almaimf`

So, if you want to start with the ALMAIMF code directory in your path, you can do it two ways:
1. Shell variable:
```
PYTHONPATH=/path/to/almaimf/code casa
```
2. In CASA:
```
$ casa
CASA <1>: import sys; sys.path.append('/path/to/almaimf/code')
```

**Comment by keflavich** [comment]
I just pushed some more changes that should make the `continuum_imaging.py` and `continuum_imaging_selfcal.py` scripts much more flexible; I haven't ported that to `continuum_imaging_both.py` yet though

**Comment by rgalvanmadrid** [comment]
OK. I will use the latest version.

**Comment by keflavich** [comment]
This functionality has been merged into `continuum_imaging_selfcal.py` through other paths, so I'm closing this.

**Pull request closed without merging**
